### PR TITLE
Review the Dependencies for FHIR Term

### PR DESCRIPTION
**Pull request by prb112**
Abbreviated dep list

- [INFO] ----------------------< com.ibm.fhir:fhir-server >----------------------
- [INFO] Building fhir-server 4.7.0-SNAPSHOT                              [29/49]
- [INFO] --------------------------------[ jar ]---------------------------------
- [INFO] +- com.ibm.fhir:fhir-term-graph:jar:4.7.0-SNAPSHOT:compile
- [INFO] |  +- com.ibm.fhir:fhir-term:jar:4.7.0-SNAPSHOT:compile
- [INFO] |  +- org.janusgraph:janusgraph-core:jar:0.5.3:compile
- [INFO] |  |  +- org.janusgraph:janusgraph-driver:jar:0.5.3:compile
- X EXCLUDE |  |  |  +- org.apache.tinkerpop:gremlin-groovy:jar:3.4.6:compile
- EXCLUDE |  |  |  |  +- org.apache.ivy:ivy:jar:2.3.0:compile
- EXCLUDE |  |  |  |  +- org.codehaus.groovy:groovy-groovysh:jar:indy:2.5.7:compile
- EXCLUDE |  |  |  |  |  +- org.codehaus.groovy:groovy-cli-picocli:jar:2.5.7:compile
- EXCLUDE |  |  |  |  |  |  \- info.picocli:picocli:jar:3.9.5:compile
- EXCLUDE |  |  |  |  |  +- org.codehaus.groovy:groovy-console:jar:2.5.7:compile
- EXCLUDE |  |  |  |  |  |  +- org.codehaus.groovy:groovy-templates:jar:2.5.7:compile
- EXCLUDE |  |  |  |  |  |  |  \- org.codehaus.groovy:groovy-xml:jar:2.5.7:compile
- EXCLUDE |  |  |  |  |  |  \- org.codehaus.groovy:groovy-swing:jar:2.5.7:compile
- EXCLUDE |  |  |  |  |  \- jline:jline:jar:2.14.6:compile
- EXCLUDE |  |  |  |  +- org.codehaus.groovy:groovy-jsr223:jar:indy:2.5.7:compile
- EXCLUDE |  |  |  |  +- org.mindrot:jbcrypt:jar:0.4:compile
- [INFO] |  |  |  |  \- com.github.ben-manes.caffeine:caffeine:jar:2.3.1:compile
- X EXCLUDE |  |  |  +- org.noggit:noggit:jar:0.6:compile
- X EXCLUDE |  |  |  +- org.locationtech.spatial4j:spatial4j:jar:0.7:compile
- [INFO] |  |  |  \- org.locationtech.jts:jts-core:jar:1.16.1:compile
- [INFO] |  |  +- org.apache.tinkerpop:tinkergraph-gremlin:jar:3.4.6:compile
- X EXCLUDE |  |  +- org.glassfish:javax.json:jar:1.0:compile
- X EXCLUDE |  |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
- [INFO] |  +- org.janusgraph:janusgraph-lucene:jar:0.5.3:compile
- X EXCLUDE |  |  +- org.apache.lucene:lucene-spatial:jar:7.7.2:compile
- X EXCLUDE |  |  \- org.apache.lucene:lucene-spatial-extras:jar:7.7.2:compile
- X EXCLUDE |  |     +- org.apache.lucene:lucene-spatial3d:jar:7.7.2:compile
- X EXCLUDE |  |     \- io.sgr:s2-geometry-library-java:jar:1.0.0:compile
- [INFO] |  +- org.apache.tinkerpop:gremlin-driver:jar:3.4.6:compile
- X EXCLUDE |  |  |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:compile
- [INFO] |  |  +- io.netty:netty-all:jar:4.1.42.Final:compile
- X EXCLUDE |  |  +- org.codehaus.groovy:groovy:jar:indy:2.5.7:compile
- X EXCLUDE |  |  +- org.codehaus.groovy:groovy-json:jar:indy:2.5.7:compile
- 
Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

### CODE REVIEW

**Comment by lmsurpre** [comment]
can we exclude these directly in `fhir-term-graph` or are they needed there?

logback was excluded in fhir-server and fhir-bulkdata-webapp because we need logging in fhir-term-graph (for the loader).

if we decide not to exclude these from `fhir-term-graph` then we should exclude them from both fhir-server AND fhir-bulkdata-webapp

**Comment by lmsurpre** [comment]
FYI I asked John how tightly coupled we are to JanusGraph and this was his reply:

> FHIRTermGraph and FHIRTermGraphImpl are pretty tightly bound to Janusgraph, GraphTermServiceProvider is not

Just food for future thought (like if we wanted to split fhir-term-graph into a separate server in the future).

**Comment by prb112** [comment]
Updated per chat/conversation on Dependencies

**Review by lmsurpre — APPROVED** [review]
LGTM, but I'd like John to approve because I don't really understand the ramifications of weeding out stuff like those groovy libs

**Review by JohnTimm — APPROVED** [review]
LGTM - I don't fully understand the ramifications but I think the exclusions are innocuous.

**Pull request merged**
