### PR TITLE
Duplicate Entry on Execution of Batch with Build #1024

### PR DESCRIPTION
**Pull request by prb112**
Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

### CODE REVIEW

**Comment by albertwang-ibm** [comment]
MULTITENANT_FEATURE_ENABLED is a little bit conflict with what I'm doing to enable storeprocedure for postgresql -- postgresql db is not multi-tenant, but we do need update-procedure support for postgresql in the schema tool...

**Comment by prb112** [comment]
> MULTITENANT_FEATURE_ENABLED is a little bit conflict with what I'm doing to enable storeprocedure for postgresql -- postgresql db is not multi-tenant, but we do need update-procedure support for postgresql in the schema tool...

I get that it is confusing. If we need to update the name in the code we can. 
The point is that it looks up the feature supporting a multitenant datastore.

**Comment by albertwang-ibm** [comment]
> > MULTITENANT_FEATURE_ENABLED is a little bit conflict with what I'm doing to enable storeprocedure for postgresql -- postgresql db is not multi-tenant, but we do need update-procedure support for postgresql in the schema tool...
> 
> I get that it is confusing. If we need to update the name in the code we can.
> The point is that it looks up the feature supporting a multitenant datastore.

yes, my comment is for the schema tool only and I may have to change it. this PR looks great for me.

**Comment by prb112** [comment]
> > > MULTITENANT_FEATURE_ENABLED is a little bit conflict with what I'm doing to enable storeprocedure for postgresql -- postgresql db is not multi-tenant, but we do need update-procedure support for postgresql in the schema tool...
> > 
> > 
> > I get that it is confusing. If we need to update the name in the code we can.
> > The point is that it looks up the feature supporting a multitenant datastore.
> 
> yes, my comment is for the schema tool only and I may have to change it. this PR looks great for me.

If you change it, I'd simply suggest changing the name, and not the functionality.
It's intended to shortcircuit multiple tenants in the same datastore.  If you want to add stored procedures for Postgres, then we add a specific gate for that feature.

**Pull request merged**
