### PR TITLE
Issue #1104 - create fhir-term module

### PR DESCRIPTION
**Pull request by JohnTimm**
- Created `fhir-term` Maven module
- Moved `CodeSystemSupport` and `ValueSetSupport` to `fhir-term` module
- Created simple `FHIRTermServiceProvider` SPI and `FHIRTermService` singleton class
- Created `DefaultTermServiceProvider` that uses `ValueSetSupport` and `CodeSystemSupport` under the covers
- Moved value set expansion test cases to new `fhir-term` module
- Implemented `expand`, `lookup`, `subsumes`, `closure`, and `validateCode` in `DefaultTermServiceProvider`

Signed-off-by: John T.E. Timm <johntimm@us.ibm.com>

### CODE REVIEW

**Comment by prb112** [comment]
Please update the base README.md with a description of the module. 
Can this wait to post 4.2.2?

**Comment by JohnTimm** [comment]
> Please update the base README.md with a description of the module.
> Can this wait to post 4.2.2?

I'm find waiting until after we tag 4.2.2 but let's get it merged before we update the snapshot number in master (otherwise it will break me).

**Comment by JohnTimm** [comment]
> Does it update the validation assembly to include this new module?
> Maybe include updates to the FHIRValidationGuide (including an update to the image there)?

@prb112 will the validation assembly pick this up by virtue of transitive dependency?

**Comment by prb112** [comment]
No but I can add a PR on this to make sure it does.

**Comment by prb112** [comment]
Added https://github.com/IBM/FHIR/pull/1108

**Pull request merged**
