### PR TITLE
Extra EAR projects are created needlessly on Maven Project import #57

### PR DESCRIPTION
**Pull request by prb112**
- set jaxrs to provided

Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

### CODE REVIEW

**Comment by lmsurpre** [comment]
I made this change locally and started seeing red x in downstream modules that import this:
image

I guess we'd need to add it as dependency with provided scope in all those too?
* fhir-notification
* fhir-operation
* fhir-server
* ...

**Comment by prb112** [comment]
strange - I didn't get that on my test - I wonder if I didn't include all the pom.

**Comment by prb112** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:56 min
[INFO] Finished at: 2019-09-16T09:41:38-04:00
[INFO] ------------------------------------------------------------------------
```
Updated and ran the integration tests

**Comment by lmsurpre** [comment]
I'm guessing it is more of an eclipse issue than a maven one.
After your latest change, most of those all went away but i have just one remaining:
* fhir-operation-apply

**Comment by lmsurpre** [comment]
Why was this one closed?

**Comment by prb112** [comment]
look at the commit history, I'm not sure what our rebase differences are

**Pull request closed without merging**
