### PR TITLE
issue #1814 - add javadoc and requireNonNull in factory methods

### PR DESCRIPTION
**Pull request by lmsurpre**
Signed-off-by: Lee Surprenant <lmsurpre@us.ibm.com>

### CODE REVIEW

**Review by prb112 — APPROVED** [review]
LGTM, the CodeGenerator seems pretty straightforward

**Comment by JohnTimm** [comment]
This seems redundant as we already check for null in the constructor of the object being built.

**Review by JohnTimm — APPROVED** [review]
LGTM

**Comment by lmsurpre** [comment]
> This seems redundant as we already check for null in the constructor of the object being built.

Specifically this was the documented team decision at https://github.com/IBM/FHIR/issues/1814#issuecomment-783491677

I think the biggest benefit is that we'll get a better error message for these cases.
Additionally, I think the generated NPE is more applicable for a factory method than the previous IllegalStateException (which is more appropriate for `Builder.build()`).

**Pull request merged**
