### PR TITLE
feat: Upgrade C4BB Support to 0.1.7 #1583

### PR DESCRIPTION
**Pull request by prb112**
Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

### CODE REVIEW

**Review by lmsurpre — COMMENTED** [review]
Can we upgrade to the latest samples, too?
In version 0.1.4 we had to do a bunch of work to make them validate, so it would be a good exercise to see if they're truly fixed or not.

**Comment by prb112** [comment]
> Can we upgrade to the latest samples, too?
> In version 0.1.4 we had to do a bunch of work to make them validate, so it would be a good exercise to see if they're truly fixed or not.

I pulled the latest examples too.  Are they not showing up?

**Review by JohnTimm — APPROVED** [review]
LGTM

**Comment by lmsurpre** [comment]
> I pulled the latest examples too. Are they not showing up?
I think I just missed them in the sea of spec updates.  LGTM.

**Review by lmsurpre — APPROVED** [review]
LGTM

**Pull request merged**
