### PR TITLE
Resolve multiple _lastUpdated search parameters #1087

### PR DESCRIPTION
**Pull request by prb112**
Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

### CODE REVIEW

**Comment by JohnTimm** [comment]
Does this change the behavior when we get a parameter like this:

param1=value1,value2,value3

we need to differentiate between these two cases:
 
param1=value1,value2,value3’

and:

param1=value1&param1=value2

**Comment by lmsurpre** [comment]
Can we add a test-case that reproduces the issue and then show its been resolved?

**Comment by prb112** [comment]
Sure

**Comment by prb112** [comment]
> Does this change the behavior when we get a parameter like this:
> 
> param1=value1,value2,value3
> 
> we need to differentiate between these two cases:
> 
> param1=value1,value2,value3 (needs to be OR)
> 
> and:
> 
> param1=value1&param1=value2 (needs to be AND or not allowed)

No, it doesn't change that behavior

**Comment by prb112** [comment]
snuck in a readme per a chat with Steve/John

**Pull request merged**
