### PR TITLE
bump project modules to 4.9.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by lmsurpre**
Signed-off-by: Lee Surprenant <lmsurpre@us.ibm.com>

### CODE REVIEW

**Review by prb112 — APPROVED** [review]
LGTM,  should we push a small change to cause a rebuild?

**Comment by lmsurpre** [comment]
> LGTM, should we push a small change to cause a rebuild?

how would you feel about changing the version of fhir-examples in the parent pom so that our modules depend on 4.8.1 instead of 4.9.0-SNAPSHOT? :-)

**Comment by prb112** [comment]
> > LGTM, should we push a small change to cause a rebuild?
> 
> how would you feel about changing the version of fhir-examples in the parent pom so that our modules depend on 4.8.1 instead of 4.9.0-SNAPSHOT? :-)

I opted not to mention that; however it is my preference. We'd want to set it outside of the properties (so the automation doesn't try to reference 4.9.0-SNAPSHOT). We might need to update the build somewhat to take advantage of it.

**Comment by lmsurpre** [comment]
> > > LGTM, should we push a small change to cause a rebuild?
> > 
> > 
> > how would you feel about changing the version of fhir-examples in the parent pom so that our modules depend on 4.8.1 instead of 4.9.0-SNAPSHOT? :-)
> 
> I opted not to mention that; however it is my preference. We'd want to set it outside of the properties (so the automation doesn't try to reference 4.9.0-SNAPSHOT). We might need to update the build somewhat to take advantage of it.

I was just going to set it in the fhir-parent/pom.xml property.  I'm not sure that I understand the concern of with that, so for now I just pushed a minor change to the ISSUE_TEMPLATE to force a rebuild.

**Pull request merged**
