### PR TITLE
Control the writing of operational outcomes with https $import

### PR DESCRIPTION
**Pull request by prb112**
Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

### CODE REVIEW

**Comment by lmsurpre** [comment]
The changes look good to me, but it makes me wonder if we should at least provide a high-level summary of the resources which failed to import...any thoughts/ideas on that?

**Comment by prb112** [comment]
> The changes look good to me, but it makes me wonder if we should at least provide a high-level summary of the resources which failed to import...any thoughts/ideas on that?

Good point... I think we could do that. It shouldn't be so much of a problem

**Comment by prb112** [comment]
```

**Comment by prb112** [comment]
```
{
    "transactionTime": "2021-02-05T14:00:57.717-05:00",
    "request": "$import",
    "requiresAccessToken": false,
    "output": [
        {
            "type": "OperationOutcome",
            "url": "test-import.ndjson_oo_success.ndjson",
            "count": 4
        }
    ],
    "error": [
        {
            "type": "OperationOutcome",
            "url": "test-import.ndjson_oo_errors.ndjson",
            "count": 0
        }
    ]
* Connection #0 to host localhost left intact
}*
```

This is what is returned.

**Pull request closed without merging**
