### PR TITLE
Issue #2503 - Check resource type on $reindex operation

### PR DESCRIPTION
**Pull request by tbieste**
Issue #2503 - Check resource type on $reindex operation

Signed-off-by: Troy Biesterfeld <tbieste@us.ibm.com>

### CODE REVIEW

**Comment by lmsurpre** [comment]
Its funny, I actually recently opened https://github.com/IBM/FHIR/issues/2526 with a very similar observation.
I'm totally fine with the proposed change but I think we should more wholistically stop allowing requests to the `/Resource` and `/DomainResources`, not just for this one operation.

**Review by prb112 — APPROVED** [review]

**Comment by prb112** [comment]
Question: Should this be pushed down one level to AbstractOperation.invoke for Parameters, where it can check if the resourceType is abstract?

```
**@Override
    public final Parameters invoke(
            FHIROperationContext operationContext,
            Class<? extends Resource> resourceType,
            String logicalId, String versionId,
            Parameters parameters,
            FHIRResourceHelpers resourceHelper) throws FHIROperationException {
```

**Comment by tbieste** [comment]
> Question: Should this be pushed down one level to AbstractOperation.invoke for Parameters, where it can check if the resourceType is abstract?
> 
> ```
> **@Override
>     public final Parameters invoke(
>             FHIROperationContext operationContext,
>             Class<? extends Resource> resourceType,
>             String logicalId, String versionId,
>             Parameters parameters,
>             FHIRResourceHelpers resourceHelper) throws FHIROperationException {
> ```

I can push the check down one level in Issue #2195, which adds similar checking in a new custom operation; so that would be a good time to make it more common.

**Comment by lmsurpre** [comment]
> I can push the check down one level in Issue #2195, which adds similar checking in a new custom operation; so that would be a good time to make it more common.

Works for me.

**Pull request merged**
