### PR TITLE
issue-1525 -updated FHIRRestHelper

### PR DESCRIPTION
**Pull request by Mani-Chandu-ihe**
Added Feature to support bundle-patch requests.

### CODE REVIEW

**Comment by prb112** [comment]
@Mani-Chandu-ihe please complete the DCO 

Navigate to your branch 

Amend the Commit
`git commit --amend --no-edit --signoff`

Now your commits will have your sign off. Next run
`git push --force-with-lease origin issue-1525`

**Comment by JohnTimm** [comment]
We should include some server integration tests for this feature.

**Comment by prb112** [comment]
@Mani-Chandu-ihe please fix the DCO

https://github.com/IBM/FHIR/pull/1917/checks?check_run_id=1857603801

**Comment by Mani-Chandu-ihe** [comment]
> @Mani-Chandu-ihe please fix the DCO
> 
> Please follow these instructions - https://github.com/IBM/FHIR/pull/1917/checks?check_run_id=1857603801

**Pull request closed without merging**
