### PR TITLE
Update RestAuditLogger to use status to switch RAL type

### PR DESCRIPTION
**Pull request by prb112**
Ran with Test cases

Method: Post 
Url: https://localhost:9443/fhir-server/api/v4/Patient/17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f

```
{
    "request_unique_id": "c9f8d282-ecf1-47ca-98b9-4438f18b0d51",
    "action": "C",
    "start_time": "2021-11-10 20:48:42.406",
    "end_time": "2021-11-10 20:48:45.757",
    "api_parameters": {
        "request": "/fhir-server/api/v4/Patient",
        "request_status": 201
    },
    "data": {
        "resource_type": "Patient",
        "id": "17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f",
        "version_id": "1"
    },
    "event_type": "fhir-create",
    "description": "FHIR Create request",
    "location": "0:0:0:0:0:0:0:1/localhost"
}
```

Method: PUT 
Url: https://localhost:9443/fhir-server/api/v4/Patient/17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f
Prior version

```
{
    "request_unique_id": "368944d1-accc-4601-bc97-9db6a1938613",
    "action": "U",
    "start_time": "2021-11-10 20:50:54.354",
    "end_time": "2021-11-10 20:50:55.239",
    "api_parameters": {
        "request": "/fhir-server/api/v4/Patient/17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f",
        "request_status": 200
    },
    "data": {
        "resource_type": "Patient",
        "id": "17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f",
        "version_id": "2"
    },
    "event_type": "fhir-update",
    "description": "FHIR Update request",
    "location": "0:0:0:0:0:0:0:1/localhost"
}
```

Method: PUT 
Url: https://localhost:9443/fhir-server/api/v4/Patient/17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f2
No prior version

```
{
    "request_unique_id": "f4718fca-a900-4136-a5e4-5bae563e05b0",
    "action": "C",
    "start_time": "2021-11-10 20:51:55.396",
    "end_time": "2021-11-10 20:51:55.714",
    "api_parameters": {
        "request": "/fhir-server/api/v4/Patient/17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f2",
        "request_status": 201
    },
    "data": {
        "resource_type": "Patient",
        "id": "17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f2",
        "version_id": "1"
    },
    "event_type": "fhir-create",
    "description": "FHIR Create request",
    "location": "0:0:0:0:0:0:0:1/localhost"
}
```

Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

### CODE REVIEW

**Review by lmsurpre — APPROVED** [review]
LGTM

**Comment by lmsurpre** [comment]
Question:  what do we want it to be (`C` or `U`) in the case of an update to a resource version that is currently deleted?

**Comment by prb112** [comment]
> Question: what do we want it to be (`C` or `U`) in the case of an update to a resource version that is currently deleted?

This is a delete on an existing resource. (200) 

```
{
    "request_unique_id": "dd39b46a-1323-4521-95ea-c9e9be8bfbdd",
    "action": "D",
    "start_time": "2021-11-10 21:34:27.924",
    "end_time": "2021-11-10 21:34:28.297",
    "api_parameters": {
        "request": "/fhir-server/api/v4/Patient/17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f2",
        "request_status": 200
    },
    "data": {
        "resource_type": "Patient",
        "id": "17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f2",
        "version_id": "2"
    },
    "event_type": "fhir-delete",
    "description": "FHIR Delete request",
    "location": "0:0:0:0:0:0:0:1/localhost"
}
```

PUT on that resource

```
{
    "request_unique_id": "c1943cf8-1081-431e-81a7-70c8c9a6357e",
    "action": "C",
    "start_time": "2021-11-10 21:36:23.728",
    "end_time": "2021-11-10 21:36:24.159",
    "api_parameters": {
        "request": "/fhir-server/api/v4/Patient/17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f2",
        "request_status": 201
    },
    "data": {
        "resource_type": "Patient",
        "id": "17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f2",
        "version_id": "3"
    },
    "event_type": "fhir-create",
    "description": "FHIR Create request",
    "location": "0:0:0:0:0:0:0:1/localhost"
}
```

It ends up being a Create.  I'm not sure we should make it an Update in this case. (neither seem ideal)

I'd like @d0roppe to chime in.

**Comment by lmsurpre** [comment]
To be clear, considering this either a create (C) or an update (U) is fine by me.  Since we're now populating it based on the response code, it makes sense that its calling this a create.

We probably have some more work to do if we want this to be considered a "create" across the board... for example should it call `beforeCreate` and `afterCreate` interceptor methods or `beforeUpdate` and `afterUpdate`?  I think it calls the xUpdate ones today, which means our notification event will call it an update.  I think maybe we just open a new issue to investigate / decide on that, and then call this one good...

**Comment by prb112** [comment]
> To be clear, either answer is fine by me (either `C` or `U`). Since we're now populating it based on the response code, it makes sense that we call it a create (because we currently return a 201 for this 'undelete' action).
> 
> One reason I asked is that we probably have some more work to do if we want this to be considered a "create" across the board... for example should it call `beforeCreate` and `afterCreate` interceptor methods or `beforeUpdate` and `afterUpdate`? I think it calls the update ones today. And that means our notification event will call it an update. I think maybe we just open a new issue to investigate / decide on that, and then call this one good...

That's right. They call the update ones today.  I chose to keep that part the same as it doesn't mutate or override the mapping. It's pretty clear today.  I chose to make this decision at the audit code.

**Pull request merged**
