### PR TITLE
 Expand all model tests #460

### PR DESCRIPTION
**Pull request by prb112**
Expand all model tests #460 
Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

### CODE REVIEW

**Comment by albertwang-ibm** [comment]
I didn't add the validator into R4ExampleTest.java for fhir-model project to avoid cycling dependency situation, because the ValidationProcessor is defined in fhir-validation project which depends on fhir-model project,  neither can we simply move ValidationProcessor into fhir-model projects due to that FhirValidator used by ValidationProcessor is actually defined in fhir-validation project.  Seems one option for us is to change the workflow to run all.txt index file for fhir-persistence-jdbc project whenever any project in either model-pathes or jdbc-pathes is changed...

**Comment by prb112** [comment]
Sure. since this is @lmsurpre I'll leave with him to decide on the approach

**Comment by lmsurpre** [comment]
should we have a separate test within fhir-validation which executes the validator against all the resource?

**Comment by prb112** [comment]
> should we have a separate test within fhir-validation which executes the validator against all the resource?

Sure. I think that's valid.

**Pull request closed without merging**
